### ISSUE TITLE
Possible ReDoS in Crypto or Investment Spam

### ISSUE THREAD

**Issue by PunkerGhoul** [World-Hacking-Developers/automod-regex#1]
Positive ReDoS test results are obtained in both patterns, their integration in chatbots risks the availability of the service.

```regex
(earn|mak|made).*?[\d.,]+?k
[\d.,]+?k.*?profit
```

Evidence is attached

![image](https://user-images.githubusercontent.com/40646732/224466446-321fb742-109f-45c0-ada0-81a47037230c.png)

![image](https://user-images.githubusercontent.com/40646732/224466437-3ff16b89-22d7-4157-8919-f1c84aec65e9.png)

Tool: [Devina.io](https://devina.io/redos-checker)

**Comment by fredrare** [comment]
Thanks for your report, @J020203.
In this case, the expression is analyzed by the Discord automod directly, so no problems on our side regarding availability for any bots. Also, I believe they only search for the first match, so I don't think this would cause an issue for Discord either.
